config/routes.rb
Rails.application.routes.draw do
  get "tasks", to: "tasks#index"

  get "tasks/:id", to: "tasks#show", as: :task

  get "tasks/new", to: "tasks#new", as: :new_task
  post "tasks", to: "tasks#create"

  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"

  delete "tasks/:id", to: "tasks#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/task_controller.rb
class TaskController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(set_task_params)
    redirect_to tasks_path

  end

  def edit
     @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(set_task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task_params
    params.require(:task).permit(:date, :name, :done)
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(set_task_params)
    redirect_to tasks_path

  end

  def edit
     @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(set_task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task_params
    params.require(:task).permit(:date, :name, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :date %>
  <%= f.date_field :date %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :done %>
  <%= f.check_box :done %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<% @tasks.each do |task| %>
  <h2><%=link_to task.name, task_path(task)%></h2>
  <p><%= task.date %></p>
  <p><%= task.name %></p>
  <p><%= task.done %></p>
<% end %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :date %>
  <%= f.date_field :date %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :done %>
  <%= f.check_box :done %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2>@task.name</h2>
<p><%= @task.date %></p>
<p><%= @task.name %></p>
<p><%= @task.done %></p>

<button>
  <%= link_to "Delete", task_path(task),
    method: :delete,
    data: { confirm: "Are you sure?" } %>
</button>